# Appium Server Config
appium.server.url=http://127.0.0.1:4723

# Device Configurations
platform.name=Android
automation.name=UiAutomator2
device.name=134227049L004512

# Application Configuration (Relative path from project root)
app.path=app/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk

# Explicit/Implicit Wait Times in seconds
implicit.wait=0
explicit.wait=10
